const mongoose = require('mongoose');
const Company = require('./models/Company');
require('dotenv').config();

const sampleCompanies = [
  {
    companyName: '株式会社テックイノベーション',
    industry: 'IT・通信',
    headquarters: '東京都渋谷区',
    businessDescription: 'クラウドサービスの開発・提供、AIソリューション事業を展開しています。',
    website: 'https://tech-innovation.example.com',
    email: 'recruit@tech-innovation.example.com',
    phone: '03-1234-5678',
    positionTitle: 'フルスタックエンジニア',
    employmentType: '正社員',
    jobDescription: 'React/Node.jsを用いた自社SaaSプロダクトの開発をお任せします。フロントエンドからバックエンドまで幅広く携わることができ、技術的な成長が期待できる環境です。',
    requiredSkills: 'JavaScript/TypeScriptの実務経験2年以上、React or Vue.jsの開発経験、REST APIの設計・開発経験',
    preferredSkills: 'Docker/Kubernetesの知識、AWS/GCPの利用経験、CI/CDパイプラインの構築経験',
    workLocation: '東京都渋谷区（リモートワーク可）',
    workHours: '9:00〜18:00（フレックスタイム制）',
    salaryMin: 5000000,
    salaryMax: 9000000,
    holidays: '完全週休2日制（土日祝）、年末年始、夏季休暇、有給休暇',
    benefits: '各種社会保険完備、交通費全額支給、書籍購入補助、資格取得支援制度、リモートワーク手当',
    selectionProcess: '書類選考 → 1次面接（技術面接） → 2次面接（人事面接） → 最終面接',
    status: 'active'
  },
  {
    companyName: '医療法人 さくら総合病院',
    industry: '医療',
    headquarters: '大阪府大阪市北区',
    businessDescription: '総合病院として地域医療に貢献。救急医療、がん治療、リハビリテーションに力を入れています。',
    website: 'https://sakura-hospital.example.com',
    email: 'jinji@sakura-hospital.example.com',
    phone: '06-9876-5432',
    positionTitle: '看護師（正看護師）',
    employmentType: '正社員',
    jobDescription: '病棟での看護業務全般をお任せします。チーム医療の一員として、患者様の回復をサポートしていただきます。',
    requiredSkills: '正看護師免許、基本的な看護技術',
    preferredSkills: '急性期病棟での勤務経験、専門看護師・認定看護師資格',
    workLocation: '大阪府大阪市北区',
    workHours: '8:30〜17:30（3交代制あり）',
    salaryMin: 3800000,
    salaryMax: 5500000,
    holidays: '週休2日制（シフト制）、年末年始、夏季休暇、有給休暇',
    benefits: '各種社会保険完備、退職金制度、院内保育所、看護師寮、資格取得支援、研修制度充実',
    selectionProcess: '書類選考 → 面接（1回） → 健康診断 → 内定',
    status: 'active'
  },
  {
    companyName: '社会福祉法人 あおぞら会',
    industry: '介護',
    headquarters: '神奈川県横浜市',
    businessDescription: '特別養護老人ホーム、デイサービス、訪問介護など総合的な介護サービスを提供しています。',
    website: 'https://aozora-care.example.com',
    email: 'saiyou@aozora-care.example.com',
    phone: '045-123-4567',
    positionTitle: '介護職員（介護福祉士）',
    employmentType: '正社員',
    jobDescription: '特別養護老人ホームでの介護業務全般。食事・入浴・排泄介助、レクリエーション企画など、利用者様の生活をサポートします。',
    requiredSkills: '介護福祉士資格、基本的な介護技術',
    preferredSkills: '特養での勤務経験1年以上、認知症ケア専門士',
    workLocation: '神奈川県横浜市青葉区',
    workHours: '7:00〜16:00 / 9:00〜18:00 / 11:00〜20:00（シフト制）',
    salaryMin: 3200000,
    salaryMax: 4500000,
    holidays: '週休2日制（シフト制）、年末年始、夏季休暇、有給休暇、誕生日休暇',
    benefits: '各種社会保険完備、退職金制度、資格取得支援金、処遇改善手当、夜勤手当、交通費全額支給',
    selectionProcess: '書類選考 → 施設見学 → 面接 → 内定',
    status: 'active'
  },
  {
    companyName: '大和建設株式会社',
    industry: '建設',
    headquarters: '愛知県名古屋市',
    businessDescription: 'マンション・商業施設の建設を主力事業とし、東海エリアを中心に展開しています。',
    website: 'https://yamato-kensetsu.example.com',
    email: 'hr@yamato-kensetsu.example.com',
    phone: '052-987-6543',
    positionTitle: '施工管理技士（建築）',
    employmentType: '正社員',
    jobDescription: 'マンション・商業施設の新築工事における施工管理業務。工程管理、品質管理、安全管理、予算管理をお任せします。',
    requiredSkills: '1級または2級建築施工管理技士、普通自動車免許',
    preferredSkills: '大型物件の施工管理経験、BIM/CIMの知識',
    workLocation: '愛知県名古屋市・近郊現場',
    workHours: '8:00〜17:00',
    salaryMin: 4500000,
    salaryMax: 7000000,
    holidays: '週休2日制（第2・4土曜、日曜、祝日）、GW、夏季休暇、年末年始、有給休暇',
    benefits: '各種社会保険完備、退職金制度、家族手当、住宅手当、資格取得支援制度、社用車貸与',
    selectionProcess: '書類選考 → 1次面接 → 2次面接（役員面接） → 内定',
    status: 'active'
  },
  {
    companyName: '株式会社グローバルロジスティクス',
    industry: '物流',
    headquarters: '千葉県市川市',
    businessDescription: '国内外の物流ネットワークを活用した総合物流サービスを提供しています。',
    website: 'https://global-logistics.example.com',
    email: 'recruit@global-logistics.example.com',
    phone: '047-321-8765',
    positionTitle: '物流管理スタッフ',
    employmentType: '正社員',
    jobDescription: '物流センターでの在庫管理、配送管理、システム運用などをお任せします。効率的な物流オペレーションを実現するための改善提案も歓迎します。',
    requiredSkills: 'Excel、Wordの基本操作、物流業界での実務経験1年以上',
    preferredSkills: 'WMS（倉庫管理システム）の利用経験、フォークリフト免許',
    workLocation: '千葉県市川市（物流センター）',
    workHours: '9:00〜18:00',
    salaryMin: 3500000,
    salaryMax: 5000000,
    holidays: '週休2日制（土日祝）、GW、夏季休暇、年末年始、有給休暇',
    benefits: '各種社会保険完備、交通費全額支給、制服貸与、資格取得支援制度',
    selectionProcess: '書類選考 → 面接（1回） → 適性検査 → 内定',
    status: 'active'
  },
  {
    companyName: 'ハッピーダイニング株式会社',
    industry: '外食・飲食',
    headquarters: '福岡県福岡市',
    businessDescription: '九州を中心に居酒屋チェーン「九州うまいもん酒場」を展開。地元食材にこだわった料理を提供しています。',
    website: 'https://happy-dining.example.com',
    email: 'saiyou@happy-dining.example.com',
    phone: '092-555-1234',
    positionTitle: '店舗マネージャー候補',
    employmentType: '正社員',
    jobDescription: '店舗運営全般のマネジメント業務。スタッフ育成、売上管理、食材発注、シフト作成など、将来的には複数店舗の統括をお任せします。',
    requiredSkills: '飲食店での勤務経験2年以上、基本的なPCスキル',
    preferredSkills: '店長経験、食品衛生責任者',
    workLocation: '福岡県福岡市内各店舗',
    workHours: '10:00〜23:00の間でシフト制（実働8時間）',
    salaryMin: 3300000,
    salaryMax: 4800000,
    holidays: '月8日休み（シフト制）、有給休暇、特別休暇',
    benefits: '各種社会保険完備、交通費支給、食事補助（まかない）、昇給年2回、インセンティブ制度',
    selectionProcess: '書類選考 → 面接（1回） → 店舗体験 → 内定',
    status: 'active'
  },
  {
    companyName: '日本精密製造株式会社',
    industry: '製造',
    headquarters: '静岡県浜松市',
    businessDescription: '自動車部品、産業機械部品の精密加工を行う製造メーカーです。',
    website: 'https://nippon-seimitsu.example.com',
    email: 'jinji@nippon-seimitsu.example.com',
    phone: '053-444-7890',
    positionTitle: '機械加工オペレーター',
    employmentType: '正社員',
    jobDescription: 'NC旋盤、マシニングセンタを使用した金属部品の加工業務。未経験の方にも丁寧に指導します。',
    requiredSkills: '製造業での勤務経験（未経験可）',
    preferredSkills: 'NC旋盤、マシニングセンタの操作経験、図面読解スキル',
    workLocation: '静岡県浜松市北区',
    workHours: '8:00〜17:00（残業あり）',
    salaryMin: 3000000,
    salaryMax: 4500000,
    holidays: '週休2日制（土日）、GW、夏季休暇、年末年始、有給休暇',
    benefits: '各種社会保険完備、退職金制度、家族手当、住宅手当、資格取得支援制度、作業服貸与',
    selectionProcess: '書類選考 → 面接 → 工場見学 → 内定',
    status: 'active'
  },
  {
    companyName: '株式会社エデュケーションプラス',
    industry: '教育',
    headquarters: '東京都新宿区',
    businessDescription: '小中学生向けの学習塾を首都圏に20校展開。個別指導と集団指導を組み合わせた独自のカリキュラムを提供しています。',
    website: 'https://education-plus.example.com',
    email: 'recruit@education-plus.example.com',
    phone: '03-6789-0123',
    positionTitle: '塾講師（数学・英語）',
    employmentType: '正社員',
    jobDescription: '小中学生への学習指導、進路相談、保護者面談などをお任せします。個別指導または集団指導のいずれかを選択可能です。',
    requiredSkills: '大卒以上、数学または英語の指導が可能な方',
    preferredSkills: '教員免許、塾講師経験1年以上',
    workLocation: '東京都・神奈川県内の各教室',
    workHours: '13:00〜22:00（授業スケジュールにより変動）',
    salaryMin: 3200000,
    salaryMax: 5000000,
    holidays: '週休2日制（日曜+平日1日）、GW、夏季休暇、年末年始、有給休暇',
    benefits: '各種社会保険完備、交通費全額支給、研修制度充実、昇給年1回、賞与年2回',
    selectionProcess: '書類選考 → 筆記試験（専門科目） → 面接 → 模擬授業 → 内定',
    status: 'active'
  },
  {
    companyName: 'スマイルリテール株式会社',
    industry: '小売',
    headquarters: '大阪府大阪市中央区',
    businessDescription: '関西を中心にドラッグストア「スマイル薬局」を50店舗展開しています。',
    website: 'https://smile-retail.example.com',
    email: 'hr@smile-retail.example.com',
    phone: '06-5555-6789',
    positionTitle: '店舗スタッフ（登録販売者）',
    employmentType: '正社員',
    jobDescription: '医薬品・日用品の販売、品出し、レジ業務、在庫管理などをお任せします。登録販売者として医薬品の接客・相談対応も行います。',
    requiredSkills: '登録販売者資格',
    preferredSkills: 'ドラッグストアでの勤務経験、販売士資格',
    workLocation: '大阪府・兵庫県内の各店舗',
    workHours: '9:00〜22:00の間でシフト制（実働8時間）',
    salaryMin: 2800000,
    salaryMax: 3800000,
    holidays: '月8〜9日休み（シフト制）、有給休暇',
    benefits: '各種社会保険完備、交通費支給、社員割引制度、資格手当、昇給年1回、賞与年2回',
    selectionProcess: '書類選考 → 面接（1回） → 内定',
    status: 'active'
  },
  {
    companyName: 'ファーストファイナンシャル株式会社',
    industry: '金融',
    headquarters: '東京都千代田区',
    businessDescription: '個人・法人向けの金融コンサルティング、資産運用アドバイスを提供しています。',
    website: 'https://first-financial.example.com',
    email: 'career@first-financial.example.com',
    phone: '03-3210-9876',
    positionTitle: 'ファイナンシャルプランナー',
    employmentType: '正社員',
    jobDescription: '個人のお客様の資産形成・運用に関するコンサルティング業務。ライフプランニング、保険、投資、税務など幅広い分野でサポートします。',
    requiredSkills: 'FP2級以上、金融業界での実務経験1年以上',
    preferredSkills: 'FP1級、証券外務員資格、生命保険募集人資格',
    workLocation: '東京都千代田区（在宅勤務制度あり）',
    workHours: '9:00〜18:00',
    salaryMin: 4000000,
    salaryMax: 7000000,
    holidays: '完全週休2日制（土日祝）、GW、夏季休暇、年末年始、有給休暇',
    benefits: '各種社会保険完備、交通費全額支給、資格取得支援金、インセンティブ制度、企業型確定拠出年金',
    selectionProcess: '書類選考 → 適性検査 → 1次面接 → 2次面接 → 最終面接',
    status: 'active'
  },
  {
    companyName: 'パシフィックトレーディング株式会社',
    industry: 'その他',
    headquarters: '神奈川県横浜市',
    businessDescription: '輸入雑貨・家具の企画・販売を行う専門商社です。ヨーロッパ・アジアから厳選した商品を取り扱っています。',
    website: 'https://pacific-trading.example.com',
    email: 'recruit@pacific-trading.example.com',
    phone: '045-777-8888',
    positionTitle: '貿易事務スタッフ',
    employmentType: '正社員',
    jobDescription: '輸入業務に関する事務全般。通関手続き、船積書類作成、在庫管理、海外サプライヤーとのメール対応などをお任せします。',
    requiredSkills: '貿易事務の基礎知識、ビジネスレベルの英語力（TOEIC700点以上目安）',
    preferredSkills: '貿易実務検定、通関士資格、中国語スキル',
    workLocation: '神奈川県横浜市西区',
    workHours: '9:00〜18:00',
    salaryMin: 3300000,
    salaryMax: 4800000,
    holidays: '完全週休2日制（土日祝）、GW、夏季休暇、年末年始、有給休暇',
    benefits: '各種社会保険完備、交通費全額支給、語学学習支援制度、昇給年1回、賞与年2回',
    selectionProcess: '書類選考 → 英語試験 → 1次面接 → 2次面接 → 内定',
    status: 'active'
  }
];

async function seedCompanies() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('MongoDB接続成功');

    // 既存のデータを削除
    await Company.deleteMany({});
    console.log('既存の企業データを削除しました');

    // サンプルデータを挿入
    await Company.insertMany(sampleCompanies);
    console.log(`${sampleCompanies.length}件の企業データを登録しました`);

    mongoose.connection.close();
    console.log('完了');
  } catch (error) {
    console.error('エラー:', error);
    process.exit(1);
  }
}

seedCompanies();
